# Generated by Django 5.2.17 on 2026-09-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Ya existe una cuenta con este nombre."},
                max_length=150,
                unique=True,
                verbose_name="nombre o empresa",
            ),
        ),
    ]
